added tests of basic structures and atoms

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,30 +1,46 @@
 #!/bin/bash
 root=`dirname $(dirname $(pwd)/$0)`
 let fail=0
+let tests=0
+let run=0
 mkdir "${root}/tmp"
 tput setaf 1
 for test_file in $(ls ${root}/test)
 do
   test_name="${test_file%.*}"
-  clang ${root}/test/${test_file} -o ${root}/tmp/${test_name}
-  ${root}/tmp/${test_name} | head -n 1
-  if [ $? -ne 0 ]; then
+  clang ${root}/test/${test_file} -o ${root}/tmp/${test_name} >& /dev/null
+  if [[ ! -e ${root}/tmp/${test_name} ]]; then
+    echo "Compile Error: $test_file"
+    let tests=$tests+1
     let fail=$fail+1
   fi
 done
+for test in $(ls ${root}/tmp)
+do
+  let run=$run+1
+  let tests=$tests+1
+  $(${root}/tmp/${test}) >& /dev/null
+  if [ ${PIPESTATUS[0]} -ne 0 ]; then
+    let fail=$fail+1
+    echo "Fail: $test"
+  fi
+done
 rm -rf ${root}/tmp
-tput bold
 if [ $fail -eq 0 ]; then
   tput setaf 2
+  echo "$tests Passed"
+  tput bold
   echo "OK"
 elif [ $fail -eq 1 ]; then
   echo
   tput setaf 1
-  echo "1 Failure"
+  tput bold
+  echo "$tests Tests Found, $run Tests Run, 1 Failure"
 else
   echo
   tput setaf 1
-  echo "$fail Failures"
+  tput bold
+  echo "$tests Tests Found, $run Tests Run, $fail Failures"
 fi
 tput sgr0
 exit $fail
